---
version: "3.4"

services:
  server:
    build:
      context: server/
      args:
        ZABBIX_VERSION: 7.0
        ZABBIX_REVISION: 2
    cap_add:
      - SYS_NICE  # required for MySQL
    ports:
      - "127.0.0.1:8080:8080"  # web frontend
    secrets:
      - mysqlrootpw
      - mysqlzabbixpw

  client:
    deploy:
      replicas: 3
    build:
      context: client/
      args:
        ZABBIX_VERSION: 7.0
        ZABBIX_REVISION: 2

secrets:
  mysqlrootpw:
    file: .mysql-root-pw
  mysqlzabbixpw:
    file: .mysql-zabbix-pw
